export const competitions = {
  "garcons":[

],
  "filles":[

],
  "hommes":[
  {
    "id":1623255,
    "nom":"GASTES TC 1",
    "codeClub":"59400240",
    "hLib":"CD 40 - COUPE D'HIVER MESSIEURS 2019",
    "sexe":"H",
    "categorieAge":"Senior",
    "ageMin":19,
    "ageMax":34,
    "division":"DIVISION 2",
    "phases":[
      {
        "phase":{
          "phase":{
            "id":147155,
            "nom":"PHASE PRELIMINAIRE",
            "preliminaire":true,
            "tableau":false,
            "tailleDuTableau":0,
            "nombreDeTours":0,
            "allerRetour":false
          },
          "poule":{
            "id":352373,
            "nom":"POULE B",
            "lettre":" B"
          }
        },
        "rencontres":[
          null,
          "D",
          null
        ]
      }
    ]
  },
  {
    "id":1623256,
    "nom":"GASTES TC 2",
    "codeClub":"59400240",
    "hLib":"CD 40 - COUPE D'HIVER MESSIEURS 2019",
    "sexe":"H",
    "categorieAge":"Senior",
    "ageMin":19,
    "ageMax":34,
    "division":"DIVISION 5",
    "phases":[
      {
        "phase":{
          "phase":{
            "id":147152,
            "nom":"PHASE PRELIMINAIRE",
            "preliminaire":true,
            "tableau":false,
            "tailleDuTableau":0,
            "nombreDeTours":0,
            "allerRetour":false
          },
          "poule":{
            "id":352395,
            "nom":"POULE A",
            "lettre":" A"
          }
        },
        "rencontres":[
          "V",
          "V",
          null
        ]
      }
    ]
  },
  {
    "id":1623258,
    "nom":"GASTES TC 3",
    "codeClub":"59400240",
    "hLib":"CD 40 - COUPE D'HIVER MESSIEURS 2019",
    "sexe":"H",
    "categorieAge":"Senior",
    "ageMin":19,
    "ageMax":34,
    "division":"DIVISION 8",
    "phases":[
      {
        "phase":{
          "phase":{
            "id":147149,
            "nom":"PHASE PRELIMINAIRE",
            "preliminaire":true,
            "tableau":false,
            "tailleDuTableau":0,
            "nombreDeTours":0,
            "allerRetour":false
          },
          "poule":{
            "id":352415,
            "nom":"POULE A",
            "lettre":" A"
          }
        },
        "rencontres":[
          "V",
          null,
          null
        ]
      }
    ]
  }
],
  "femmes":[
  {
    "id":1623248,
    "nom":"GASTES TC 1",
    "codeClub":"59400240",
    "hLib":"CD 40 - COUPE D'HIVER DAMES 2019",
    "sexe":"F",
    "categorieAge":"Senior",
    "ageMin":19,
    "ageMax":34,
    "division":"DIVISION 1",
    "phases":[
      {
        "phase":{
          "phase":{
            "id":147170,
            "nom":"PHASE PRELIMINAIRE",
            "preliminaire":true,
            "tableau":false,
            "tailleDuTableau":0,
            "nombreDeTours":0,
            "allerRetour":false
          },
          "poule":{
            "id":352437,
            "nom":"POULE C",
            "lettre":" C"
          }
        },
        "rencontres":[
          "V",
          null,
          null
        ]
      }
    ]
  }
],
  "hommesPlus":[
  {
    "id":1598809,
    "nom":"GASTES TC 1",
    "codeClub":"59400240",
    "hLib":"CD 40 - INTERCLUBS 35+ MESSIEURS 2019",
    "sexe":"H",
    "categorieAge":"35",
    "ageMin":35,
    "ageMax":39,
    "division":"DIVISION 3",
    "phases":[
      {
        "phase":{
          "phase":{
            "id":145153,
            "nom":"PHASE PRELIMINAIRE",
            "preliminaire":true,
            "tableau":false,
            "tailleDuTableau":0,
            "nombreDeTours":0,
            "allerRetour":false
          },
          "poule":{
            "id":347751,
            "nom":"POULE A",
            "lettre":" A"
          }
        },
        "rencontres":[
          null,
          "V",
          "D",
          "V",
          "V"
        ]
      }
    ]
  },
  {
    "id":1598811,
    "nom":"GASTES TC 2",
    "codeClub":"59400240",
    "hLib":"CD 40 - INTERCLUBS 35+ MESSIEURS 2019",
    "sexe":"H",
    "categorieAge":"35",
    "ageMin":35,
    "ageMax":39,
    "division":"DIVISION 7",
    "phases":[
      {
        "phase":{
          "phase":{
            "id":145149,
            "nom":"PHASE PRELIMINAIRE",
            "preliminaire":true,
            "tableau":false,
            "tailleDuTableau":0,
            "nombreDeTours":0,
            "allerRetour":false
          },
          "poule":{
            "id":347759,
            "nom":"POULE A",
            "lettre":" A"
          }
        },
        "rencontres":[
          "V",
          "N",
          "V",
          null,
          "V"
        ]
      },
      {
        "phase":{
          "phase":{
            "id":147637,
            "nom":"PHASE FINALE",
            "preliminaire":false,
            "tableau":true,
            "tailleDuTableau":2,
            "nombreDeTours":1,
            "allerRetour":false
          },
          "poule":null
        },
        "rencontres":[
          "D"
        ]
      }
    ]
  }
],
  "femmesPlus":[
  {
    "id":1598807,
    "nom":"GASTES TC 1",
    "codeClub":"59400240",
    "hLib":"CD 40 - INTERCLUBS 35+ DAMES 2019",
    "sexe":"F",
    "categorieAge":"35",
    "ageMin":35,
    "ageMax":39,
    "division":"DIVISION 3",
    "phases":[
      {
        "phase":{
          "phase":{
            "id":145172,
            "nom":"PHASE PRELIMINAIRE",
            "preliminaire":true,
            "tableau":false,
            "tailleDuTableau":0,
            "nombreDeTours":0,
            "allerRetour":false
          },
          "poule":{
            "id":347767,
            "nom":"POULE A",
            "lettre":" A"
          }
        },
        "rencontres":[
          "N",
          "D",
          "D",
          "D",
          "N"
        ]
      }
    ]
  }
]
}

export const detailCompetition = {
  "phases":[
  {
    "phase":{
      "phase":{
        "id":145149,
        "nom":"PHASE PRELIMINAIRE",
        "preliminaire":true,
        "tableau":false,
        "tailleDuTableau":0,
        "nombreDeTours":0,
        "allerRetour":false
      },
      "poule":{
        "id":347759,
        "nom":"POULE A",
        "lettre":" A"
      }
    },
    "rencontres":[
      {
        "id":6455501,
        "codeClubAccueil":"59400035",
        "idPhase":145149,
        "position":1,
        "place":null,
        "equipe1":{
          "id":1600305,
          "codeClub":"59400035",
          "numero":2,
          "classement":0
        },
        "score1":0,
        "disqualification1":false,
        "equipe2":{
          "id":1607307,
          "codeClub":"59649247",
          "numero":1,
          "classement":0
        },
        "score2":0,
        "disqualification2":false,
        "equipeCenseeRecevoir":1,
        "inversee":false,
        "dateTheorique":"2018-09-23T00:00:00",
        "dateReelle":"2018-09-23T00:00:00",
        "resultat":null,
        "equipeForfait":null
      },
      {
        "id":6455503,
        "codeClubAccueil":"59400131",
        "idPhase":145149,
        "position":1,
        "place":null,
        "equipe1":{
          "id":1598872,
          "codeClub":"59400131",
          "numero":2,
          "classement":0
        },
        "score1":1,
        "disqualification1":false,
        "equipe2":{
          "id":1602037,
          "codeClub":"59400148",
          "numero":1,
          "classement":0
        },
        "score2":3,
        "disqualification2":false,
        "equipeCenseeRecevoir":1,
        "inversee":false,
        "dateTheorique":"2018-09-23T00:00:00",
        "dateReelle":"2018-09-23T00:00:00",
        "resultat":"D",
        "equipeForfait":null
      },
      {
        "id":6455506,
        "codeClubAccueil":"59400240",
        "idPhase":145149,
        "position":1,
        "place":null,
        "equipe1":{
          "id":1598811,
          "codeClub":"59400240",
          "numero":2,
          "classement":0
        },
        "score1":3,
        "disqualification1":false,
        "equipe2":{
          "id":1604549,
          "codeClub":"59400078",
          "numero":3,
          "classement":0
        },
        "score2":1,
        "disqualification2":false,
        "equipeCenseeRecevoir":1,
        "inversee":false,
        "dateTheorique":"2018-09-23T00:00:00",
        "dateReelle":"2018-09-23T00:00:00",
        "resultat":"V",
        "equipeForfait":null
      },
      {
        "id":6455497,
        "codeClubAccueil":"59400078",
        "idPhase":145149,
        "position":2,
        "place":null,
        "equipe1":{
          "id":1604549,
          "codeClub":"59400078",
          "numero":3,
          "classement":0
        },
        "score1":3,
        "disqualification1":false,
        "equipe2":{
          "id":1600305,
          "codeClub":"59400035",
          "numero":2,
          "classement":0
        },
        "score2":1,
        "disqualification2":false,
        "equipeCenseeRecevoir":1,
        "inversee":false,
        "dateTheorique":"2018-09-30T00:00:00",
        "dateReelle":"2018-09-30T00:00:00",
        "resultat":"V",
        "equipeForfait":null
      },
      {
        "id":6455499,
        "codeClubAccueil":"59400148",
        "idPhase":145149,
        "position":2,
        "place":null,
        "equipe1":{
          "id":1602037,
          "codeClub":"59400148",
          "numero":1,
          "classement":0
        },
        "score1":2,
        "disqualification1":false,
        "equipe2":{
          "id":1598811,
          "codeClub":"59400240",
          "numero":2,
          "classement":0
        },
        "score2":2,
        "disqualification2":false,
        "equipeCenseeRecevoir":1,
        "inversee":false,
        "dateTheorique":"2018-09-30T00:00:00",
        "dateReelle":"2018-09-30T00:00:00",
        "resultat":"N",
        "equipeForfait":null
      },
      {
        "id":6455509,
        "codeClubAccueil":"59649247",
        "idPhase":145149,
        "position":2,
        "place":null,
        "equipe1":{
          "id":1607307,
          "codeClub":"59649247",
          "numero":1,
          "classement":0
        },
        "score1":0,
        "disqualification1":false,
        "equipe2":{
          "id":1598872,
          "codeClub":"59400131",
          "numero":2,
          "classement":0
        },
        "score2":0,
        "disqualification2":false,
        "equipeCenseeRecevoir":1,
        "inversee":false,
        "dateTheorique":"2018-09-30T00:00:00",
        "dateReelle":"2018-09-30T00:00:00",
        "resultat":null,
        "equipeForfait":null
      },
      {
        "id":6455504,
        "codeClubAccueil":"59400035",
        "idPhase":145149,
        "position":3,
        "place":null,
        "equipe1":{
          "id":1600305,
          "codeClub":"59400035",
          "numero":2,
          "classement":0
        },
        "score1":0,
        "disqualification1":false,
        "equipe2":{
          "id":1602037,
          "codeClub":"59400148",
          "numero":1,
          "classement":0
        },
        "score2":4,
        "disqualification2":false,
        "equipeCenseeRecevoir":1,
        "inversee":false,
        "dateTheorique":"2018-10-07T00:00:00",
        "dateReelle":"2018-10-07T00:00:00",
        "resultat":"D",
        "equipeForfait":null
      },
      {
        "id":6455507,
        "codeClubAccueil":"59649247",
        "idPhase":145149,
        "position":3,
        "place":null,
        "equipe1":{
          "id":1607307,
          "codeClub":"59649247",
          "numero":1,
          "classement":0
        },
        "score1":0,
        "disqualification1":false,
        "equipe2":{
          "id":1604549,
          "codeClub":"59400078",
          "numero":3,
          "classement":0
        },
        "score2":0,
        "disqualification2":false,
        "equipeCenseeRecevoir":1,
        "inversee":false,
        "dateTheorique":"2018-10-07T00:00:00",
        "dateReelle":"2018-10-07T00:00:00",
        "resultat":null,
        "equipeForfait":null
      },
      {
        "id":6455510,
        "codeClubAccueil":"59400240",
        "idPhase":145149,
        "position":3,
        "place":null,
        "equipe1":{
          "id":1598811,
          "codeClub":"59400240",
          "numero":2,
          "classement":0
        },
        "score1":4,
        "disqualification1":false,
        "equipe2":{
          "id":1598872,
          "codeClub":"59400131",
          "numero":2,
          "classement":0
        },
        "score2":0,
        "disqualification2":false,
        "equipeCenseeRecevoir":1,
        "inversee":false,
        "dateTheorique":"2018-10-07T00:00:00",
        "dateReelle":"2018-10-21T00:00:00",
        "resultat":"V",
        "equipeForfait":null
      },
      {
        "id":6455498,
        "codeClubAccueil":"59400131",
        "idPhase":145149,
        "position":4,
        "place":null,
        "equipe1":{
          "id":1598872,
          "codeClub":"59400131",
          "numero":2,
          "classement":0
        },
        "score1":1,
        "disqualification1":false,
        "equipe2":{
          "id":1600305,
          "codeClub":"59400035",
          "numero":2,
          "classement":0
        },
        "score2":3,
        "disqualification2":false,
        "equipeCenseeRecevoir":1,
        "inversee":false,
        "dateTheorique":"2018-10-14T00:00:00",
        "dateReelle":"2018-10-14T00:00:00",
        "resultat":"D",
        "equipeForfait":null
      },
      {
        "id":6455502,
        "codeClubAccueil":"59400240",
        "idPhase":145149,
        "position":4,
        "place":null,
        "equipe1":{
          "id":1598811,
          "codeClub":"59400240",
          "numero":2,
          "classement":0
        },
        "score1":0,
        "disqualification1":false,
        "equipe2":{
          "id":1607307,
          "codeClub":"59649247",
          "numero":1,
          "classement":0
        },
        "score2":0,
        "disqualification2":false,
        "equipeCenseeRecevoir":1,
        "inversee":false,
        "dateTheorique":"2018-10-14T00:00:00",
        "dateReelle":"2018-10-14T00:00:00",
        "resultat":null,
        "equipeForfait":null
      },
      {
        "id":6455508,
        "codeClubAccueil":"59400148",
        "idPhase":145149,
        "position":4,
        "place":null,
        "equipe1":{
          "id":1602037,
          "codeClub":"59400148",
          "numero":1,
          "classement":0
        },
        "score1":3,
        "disqualification1":false,
        "equipe2":{
          "id":1604549,
          "codeClub":"59400078",
          "numero":3,
          "classement":0
        },
        "score2":1,
        "disqualification2":false,
        "equipeCenseeRecevoir":1,
        "inversee":false,
        "dateTheorique":"2018-10-14T00:00:00",
        "dateReelle":"2018-10-14T00:00:00",
        "resultat":"V",
        "equipeForfait":null
      },
      {
        "id":6455500,
        "codeClubAccueil":"59400035",
        "idPhase":145149,
        "position":5,
        "place":null,
        "equipe1":{
          "id":1600305,
          "codeClub":"59400035",
          "numero":2,
          "classement":0
        },
        "score1":0,
        "disqualification1":false,
        "equipe2":{
          "id":1598811,
          "codeClub":"59400240",
          "numero":2,
          "classement":0
        },
        "score2":4,
        "disqualification2":false,
        "equipeCenseeRecevoir":1,
        "inversee":false,
        "dateTheorique":"2018-11-04T00:00:00",
        "dateReelle":"2018-11-04T00:00:00",
        "resultat":"D",
        "equipeForfait":null
      },
      {
        "id":6455505,
        "codeClubAccueil":"59649247",
        "idPhase":145149,
        "position":5,
        "place":null,
        "equipe1":{
          "id":1607307,
          "codeClub":"59649247",
          "numero":1,
          "classement":0
        },
        "score1":0,
        "disqualification1":false,
        "equipe2":{
          "id":1602037,
          "codeClub":"59400148",
          "numero":1,
          "classement":0
        },
        "score2":0,
        "disqualification2":false,
        "equipeCenseeRecevoir":1,
        "inversee":false,
        "dateTheorique":"2018-11-04T00:00:00",
        "dateReelle":"2018-11-04T00:00:00",
        "resultat":null,
        "equipeForfait":null
      },
      {
        "id":6455511,
        "codeClubAccueil":"59400078",
        "idPhase":145149,
        "position":5,
        "place":null,
        "equipe1":{
          "id":1604549,
          "codeClub":"59400078",
          "numero":3,
          "classement":0
        },
        "score1":3,
        "disqualification1":false,
        "equipe2":{
          "id":1598872,
          "codeClub":"59400131",
          "numero":2,
          "classement":0
        },
        "score2":1,
        "disqualification2":false,
        "equipeCenseeRecevoir":1,
        "inversee":false,
        "dateTheorique":"2018-11-04T00:00:00",
        "dateReelle":"2018-11-04T00:00:00",
        "resultat":"V",
        "equipeForfait":null
      }
    ],
    "detailsEquipes":[
      {
        "idEquipe":1600305,
        "numero":2,
        "club":{
          "nom":"PARENTIS EN BORN TC",
          "code":"59400035",
          "courriel":"59400035@fft.fr",
          "lat":44.35308,
          "lng":-1.07209,
          "correspondantClub":{
            "nomCorresp":"Monsieur Jean Paul LEBOUTEILLER",
            "adresse1Corresp":null,
            "adresse2Corresp":"103 avenue Georges Clemenceau",
            "codePostalCorresp":"40160",
            "villeCorresp":"PARENTIS EN BORN",
            "telBureauCorresp":null,
            "telDomicileCorresp":"0558784240",
            "telPortableCorresp":"0631686582",
            "courrielCorresp":"jean-paul.lebouteiller@9online.fr"
          },
          "site":{
            "adresse1":null,
            "adresse2":"Avenue Germinal",
            "codePostal":"40160",
            "ville":"PARENTIS-EN-BORN",
            "telephone":"0558784715",
            "nbCourtInt":2,
            "nbCourtExt":4,
            "lng":-1.07209,
            "lat":44.35308
          }
        },
        "joueurs":[
          {
            "id":3735833,
            "classementSimpleLibelle":"30/1",
            "classementDoubleLibelle":"13",
            "niveauLibelle":null,
            "brule":false,
            "qualifieProvisoire":false,
            "assimileUe":false,
            "ordre":0,
            "nom":"GLIZE",
            "prenom":"Sébastien",
            "licence":3125823,
            "ageReel":34
          },
          {
            "id":3735829,
            "classementSimpleLibelle":"30/2",
            "classementDoubleLibelle":"14",
            "niveauLibelle":null,
            "brule":false,
            "qualifieProvisoire":false,
            "assimileUe":false,
            "ordre":0,
            "nom":"GUILBERT",
            "prenom":"Emmanuel",
            "licence":1060397,
            "ageReel":49
          },
          {
            "id":3735830,
            "classementSimpleLibelle":"30/4",
            "classementDoubleLibelle":"16",
            "niveauLibelle":null,
            "brule":false,
            "qualifieProvisoire":false,
            "assimileUe":false,
            "ordre":0,
            "nom":"RIVIERE",
            "prenom":"REGIS",
            "licence":3516696,
            "ageReel":47
          },
          {
            "id":3735828,
            "classementSimpleLibelle":"30/4",
            "classementDoubleLibelle":"16",
            "niveauLibelle":null,
            "brule":false,
            "qualifieProvisoire":false,
            "assimileUe":false,
            "ordre":0,
            "nom":"DUPIS",
            "prenom":"Jean-Marie",
            "licence":4140328,
            "ageReel":45
          },
          {
            "id":3735832,
            "classementSimpleLibelle":"30/4",
            "classementDoubleLibelle":"16",
            "niveauLibelle":null,
            "brule":false,
            "qualifieProvisoire":false,
            "assimileUe":false,
            "ordre":0,
            "nom":"GLEONEC",
            "prenom":"Olivier",
            "licence":4604311,
            "ageReel":49
          },
          {
            "id":3735827,
            "classementSimpleLibelle":"30/5",
            "classementDoubleLibelle":"17",
            "niveauLibelle":null,
            "brule":false,
            "qualifieProvisoire":false,
            "assimileUe":false,
            "ordre":0,
            "nom":"MALDAT",
            "prenom":"Mickael",
            "licence":3561004,
            "ageReel":39
          },
          {
            "id":3735831,
            "classementSimpleLibelle":"30/5",
            "classementDoubleLibelle":"17",
            "niveauLibelle":null,
            "brule":false,
            "qualifieProvisoire":false,
            "assimileUe":false,
            "ordre":0,
            "nom":"DELAFLOR",
            "prenom":"samuel",
            "licence":9376951,
            "ageReel":45
          }
        ],
        "correspondant":{
          "nom":"M    Sébastien GLIZE",
          "adresse1":null,
          "adresse2":"7A rue du hameau de la forge",
          "codePostal":"33830",
          "ville":"LUGOS",
          "email":"zoxo7@orange.fr",
          "telPerso":null,
          "telPortable":"0658441781",
          "telPro":null
        }
      },
      {
        "idEquipe":1598872,
        "numero":2,
        "club":{
          "nom":"YCHOUX TC",
          "code":"59400131",
          "courriel":"tennis.ychoux@wanadoo.fr",
          "lat":44.32911,
          "lng":-0.95798,
          "correspondantClub":{
            "nomCorresp":"Madame Mickael GALOPIN",
            "adresse1Corresp":null,
            "adresse2Corresp":"3 rue des Eglantines",
            "codePostalCorresp":"40160",
            "villeCorresp":"YCHOUX",
            "telBureauCorresp":null,
            "telDomicileCorresp":null,
            "telPortableCorresp":"0632973588",
            "courrielCorresp":"m.galopin@wanadoo.fr"
          },
          "site":{
            "adresse1":"stade municipal",
            "adresse2":"rue felix arnaudin",
            "codePostal":"40160",
            "ville":"YCHOUX",
            "telephone":"0558823097",
            "nbCourtInt":1,
            "nbCourtExt":2,
            "lng":-0.95798,
            "lat":44.32911
          }
        },
        "joueurs":[
          {
            "id":3731589,
            "classementSimpleLibelle":"30/3",
            "classementDoubleLibelle":"15",
            "niveauLibelle":null,
            "brule":false,
            "qualifieProvisoire":false,
            "assimileUe":false,
            "ordre":0,
            "nom":"CAMPOS",
            "prenom":"Jean-Guillaume",
            "licence":1153810,
            "ageReel":48
          },
          {
            "id":3731592,
            "classementSimpleLibelle":"30/3",
            "classementDoubleLibelle":"15",
            "niveauLibelle":null,
            "brule":false,
            "qualifieProvisoire":false,
            "assimileUe":false,
            "ordre":0,
            "nom":"LAMARQUE",
            "prenom":"Bruno",
            "licence":5725585,
            "ageReel":53
          },
          {
            "id":3740762,
            "classementSimpleLibelle":"30/4",
            "classementDoubleLibelle":"16",
            "niveauLibelle":null,
            "brule":false,
            "qualifieProvisoire":false,
            "assimileUe":false,
            "ordre":0,
            "nom":"VAUCHE",
            "prenom":"Sebastien",
            "licence":124025,
            "ageReel":40
          },
          {
            "id":3731593,
            "classementSimpleLibelle":"30/5",
            "classementDoubleLibelle":"17",
            "niveauLibelle":null,
            "brule":false,
            "qualifieProvisoire":false,
            "assimileUe":false,
            "ordre":0,
            "nom":null,
            "prenom":null,
            "licence":2053687,
            "ageReel":48
          },
          {
            "id":3731590,
            "classementSimpleLibelle":"30/5",
            "classementDoubleLibelle":"17",
            "niveauLibelle":null,
            "brule":false,
            "qualifieProvisoire":false,
            "assimileUe":false,
            "ordre":0,
            "nom":"CARRÉ",
            "prenom":"Sébastien",
            "licence":9910468,
            "ageReel":45
          },
          {
            "id":3731594,
            "classementSimpleLibelle":"40",
            "classementDoubleLibelle":"18",
            "niveauLibelle":null,
            "brule":false,
            "qualifieProvisoire":false,
            "assimileUe":false,
            "ordre":0,
            "nom":null,
            "prenom":null,
            "licence":9635415,
            "ageReel":55
          }
        ],
        "correspondant":{
          "nom":"M    Jean-Guillaume CAMPOS",
          "adresse1":null,
          "adresse2":"7 impasse des Cigales",
          "codePostal":"40160",
          "ville":"YCHOUX",
          "email":"campos.jean-guillaume@neuf.fr",
          "telPerso":null,
          "telPortable":"0631909458",
          "telPro":null
        }
      },
      {
        "idEquipe":1598811,
        "numero":2,
        "club":{
          "nom":"GASTES TC",
          "code":"59400240",
          "courriel":"09400240@fft.fr",
          "lat":44.32801,
          "lng":-1.1438,
          "correspondantClub":{
            "nomCorresp":"Monsieur cedric gauthier",
            "adresse1Corresp":null,
            "adresse2Corresp":"94 rue des galips",
            "codePostalCorresp":"40160",
            "villeCorresp":"parentis en born",
            "telBureauCorresp":null,
            "telDomicileCorresp":null,
            "telPortableCorresp":"0622092426",
            "courrielCorresp":"gauthiercedric9991@neuf.fr"
          },
          "site":{
            "adresse1":null,
            "adresse2":"rue Darmuzey",
            "codePostal":"40160",
            "ville":"GASTES",
            "telephone":"0622092426",
            "nbCourtInt":1,
            "nbCourtExt":4,
            "lng":-1.1438,
            "lat":44.32801
          }
        },
        "joueurs":[
          {
            "id":3731387,
            "classementSimpleLibelle":"30/1",
            "classementDoubleLibelle":"13",
            "niveauLibelle":null,
            "brule":false,
            "qualifieProvisoire":false,
            "assimileUe":false,
            "ordre":0,
            "nom":"SCHWINDOWSKY",
            "prenom":"Laurent",
            "licence":6176504,
            "ageReel":49
          },
          {
            "id":3731386,
            "classementSimpleLibelle":"30/1",
            "classementDoubleLibelle":"13",
            "niveauLibelle":null,
            "brule":false,
            "qualifieProvisoire":false,
            "assimileUe":false,
            "ordre":0,
            "nom":"LOPEZ PALACIOS",
            "prenom":"STEPHANE",
            "licence":6242702,
            "ageReel":41
          },
          {
            "id":3731384,
            "classementSimpleLibelle":"30/2",
            "classementDoubleLibelle":"14",
            "niveauLibelle":null,
            "brule":false,
            "qualifieProvisoire":false,
            "assimileUe":false,
            "ordre":0,
            "nom":"CARIOU",
            "prenom":"Frederic",
            "licence":2099198,
            "ageReel":46
          },
          {
            "id":3731385,
            "classementSimpleLibelle":"30/2",
            "classementDoubleLibelle":"14",
            "niveauLibelle":null,
            "brule":false,
            "qualifieProvisoire":false,
            "assimileUe":false,
            "ordre":0,
            "nom":"DEROOST",
            "prenom":"MICHEL",
            "licence":2920841,
            "ageReel":49
          },
          {
            "id":3731389,
            "classementSimpleLibelle":"30/3",
            "classementDoubleLibelle":"15",
            "niveauLibelle":null,
            "brule":false,
            "qualifieProvisoire":false,
            "assimileUe":false,
            "ordre":0,
            "nom":"LASSERRE",
            "prenom":"Bruno",
            "licence":5120001,
            "ageReel":48
          },
          {
            "id":3731388,
            "classementSimpleLibelle":"30/3",
            "classementDoubleLibelle":"15",
            "niveauLibelle":null,
            "brule":false,
            "qualifieProvisoire":false,
            "assimileUe":false,
            "ordre":0,
            "nom":"CHAPOUL",
            "prenom":"Franck",
            "licence":5715232,
            "ageReel":45
          },
          {
            "id":3731390,
            "classementSimpleLibelle":"30/4",
            "classementDoubleLibelle":"16",
            "niveauLibelle":null,
            "brule":false,
            "qualifieProvisoire":false,
            "assimileUe":false,
            "ordre":0,
            "nom":"LAMARQUE",
            "prenom":"David",
            "licence":2972330,
            "ageReel":39
          }
        ],
        "correspondant":{
          "nom":"M    Frederic CARIOU",
          "adresse1":"270 avenue Georges clémenceau",
          "adresse2":"16 avenue georges clémenceau",
          "codePostal":"40160",
          "ville":"PARENTIS EN BORN",
          "email":"cariou.frederic@neuf.fr",
          "telPerso":"0558785507",
          "telPortable":"0650469229",
          "telPro":null
        }
      },
      {
        "idEquipe":1604549,
        "numero":3,
        "club":{
          "nom":"LABOUHEYRE JEUNESSE SPORTIVE",
          "code":"59400078",
          "courriel":"tennis.jsllabouheyre@orange.fr",
          "lat":44.19314,
          "lng":-0.91623,
          "correspondantClub":{
            "nomCorresp":"Monsieur Philippe Crosnier",
            "adresse1Corresp":null,
            "adresse2Corresp":"109 rue Emma Taris",
            "codePostalCorresp":"40210",
            "villeCorresp":"LABOUHEYRE",
            "telBureauCorresp":null,
            "telDomicileCorresp":null,
            "telPortableCorresp":"0676297580",
            "courrielCorresp":"tennis.jsllabouheyre@orange.fr"
          },
          "site":{
            "adresse1":null,
            "adresse2":null,
            "codePostal":"40210",
            "ville":"LABOUHEYRE",
            "telephone":null,
            "nbCourtInt":1,
            "nbCourtExt":3,
            "lng":-0.91623,
            "lat":44.19314
          }
        },
        "joueurs":[
          {
            "id":3748020,
            "classementSimpleLibelle":"30",
            "classementDoubleLibelle":"12",
            "niveauLibelle":null,
            "brule":false,
            "qualifieProvisoire":false,
            "assimileUe":false,
            "ordre":0,
            "nom":"VITAL",
            "prenom":"Vincent",
            "licence":7496413,
            "ageReel":35
          },
          {
            "id":3748010,
            "classementSimpleLibelle":"30/1",
            "classementDoubleLibelle":"13",
            "niveauLibelle":null,
            "brule":false,
            "qualifieProvisoire":false,
            "assimileUe":false,
            "ordre":0,
            "nom":"PARIS",
            "prenom":"Yoann",
            "licence":7222579,
            "ageReel":41
          },
          {
            "id":3748021,
            "classementSimpleLibelle":"30/2",
            "classementDoubleLibelle":"14",
            "niveauLibelle":null,
            "brule":false,
            "qualifieProvisoire":false,
            "assimileUe":false,
            "ordre":0,
            "nom":"HERVÉ",
            "prenom":"Benoit",
            "licence":9236842,
            "ageReel":36
          },
          {
            "id":3748022,
            "classementSimpleLibelle":"30/4",
            "classementDoubleLibelle":"16",
            "niveauLibelle":null,
            "brule":false,
            "qualifieProvisoire":false,
            "assimileUe":false,
            "ordre":0,
            "nom":"FARIAS",
            "prenom":"Jean-Claude",
            "licence":3041786,
            "ageReel":45
          },
          {
            "id":3748023,
            "classementSimpleLibelle":"30/5",
            "classementDoubleLibelle":"17",
            "niveauLibelle":null,
            "brule":false,
            "qualifieProvisoire":false,
            "assimileUe":false,
            "ordre":0,
            "nom":"GUILHEM",
            "prenom":"Julien",
            "licence":4257077,
            "ageReel":35
          }
        ],
        "correspondant":{
          "nom":"M    Yoann PARIS",
          "adresse1":null,
          "adresse2":"139 rue des Erables",
          "codePostal":"40210",
          "ville":"LABOUHEYRE",
          "email":"berengere40@live.fr",
          "telPerso":null,
          "telPortable":"0612848444",
          "telPro":null
        }
      },
      {
        "idEquipe":1602037,
        "numero":1,
        "club":{
          "nom":"SARBAZAN ASL",
          "code":"59400148",
          "courriel":"59400148@fft.fr                                                 ",
          "lat":44.02042,
          "lng":-0.31127,
          "correspondantClub":{
            "nomCorresp":"Madame Sandrine Beyriere",
            "adresse1Corresp":null,
            "adresse2Corresp":"71 rue du Pisque",
            "codePostalCorresp":"40120",
            "villeCorresp":"ROQUEFORT",
            "telBureauCorresp":null,
            "telDomicileCorresp":null,
            "telPortableCorresp":"0624490567",
            "courrielCorresp":"59400148@fft.fr"
          },
          "site":{
            "adresse1":null,
            "adresse2":"lotissement moneyres",
            "codePostal":"40120",
            "ville":"SARBAZAN",
            "telephone":"0558455478",
            "nbCourtInt":0,
            "nbCourtExt":2,
            "lng":-0.31127,
            "lat":44.02042
          }
        },
        "joueurs":[
          {
            "id":3739447,
            "classementSimpleLibelle":"30/1",
            "classementDoubleLibelle":"13",
            "niveauLibelle":null,
            "brule":false,
            "qualifieProvisoire":false,
            "assimileUe":false,
            "ordre":0,
            "nom":"ROZE",
            "prenom":"Jean Bernard",
            "licence":6210164,
            "ageReel":41
          },
          {
            "id":3739445,
            "classementSimpleLibelle":"30/1",
            "classementDoubleLibelle":"13",
            "niveauLibelle":null,
            "brule":false,
            "qualifieProvisoire":false,
            "assimileUe":false,
            "ordre":0,
            "nom":"ROBIN",
            "prenom":"Jean Marc",
            "licence":7902652,
            "ageReel":53
          },
          {
            "id":3750958,
            "classementSimpleLibelle":"30/2",
            "classementDoubleLibelle":"14",
            "niveauLibelle":null,
            "brule":false,
            "qualifieProvisoire":false,
            "assimileUe":false,
            "ordre":0,
            "nom":"MORA",
            "prenom":"David",
            "licence":5674927,
            "ageReel":45
          },
          {
            "id":3739444,
            "classementSimpleLibelle":"30/2",
            "classementDoubleLibelle":"14",
            "niveauLibelle":null,
            "brule":false,
            "qualifieProvisoire":false,
            "assimileUe":false,
            "ordre":0,
            "nom":"POUJAURANT",
            "prenom":"Sebastien",
            "licence":5845217,
            "ageReel":42
          },
          {
            "id":3739446,
            "classementSimpleLibelle":"30/2",
            "classementDoubleLibelle":"14",
            "niveauLibelle":null,
            "brule":false,
            "qualifieProvisoire":false,
            "assimileUe":false,
            "ordre":0,
            "nom":"ROUSSEAU",
            "prenom":"Richard",
            "licence":2363382,
            "ageReel":56
          },
          {
            "id":3739449,
            "classementSimpleLibelle":"30/3",
            "classementDoubleLibelle":"15",
            "niveauLibelle":null,
            "brule":false,
            "qualifieProvisoire":false,
            "assimileUe":false,
            "ordre":0,
            "nom":"STEYER",
            "prenom":"Dominique",
            "licence":3638213,
            "ageReel":43
          },
          {
            "id":3739448,
            "classementSimpleLibelle":"30/3",
            "classementDoubleLibelle":"15",
            "niveauLibelle":null,
            "brule":false,
            "qualifieProvisoire":false,
            "assimileUe":false,
            "ordre":0,
            "nom":"HOMBROUCKX",
            "prenom":"David",
            "licence":1930301,
            "ageReel":47
          },
          {
            "id":3739451,
            "classementSimpleLibelle":"40",
            "classementDoubleLibelle":"18",
            "niveauLibelle":null,
            "brule":false,
            "qualifieProvisoire":false,
            "assimileUe":false,
            "ordre":0,
            "nom":"CASTANEDO",
            "prenom":"Angel",
            "licence":2835044,
            "ageReel":74
          }
        ],
        "correspondant":{
          "nom":"M    michel robin",
          "adresse1":"37, place du corps Franc Pommies",
          "adresse2":null,
          "codePostal":"40120",
          "ville":"Sarbazan",
          "email":"robinmichel_robinmichel@orange.fr",
          "telPerso":null,
          "telPortable":"0688132444",
          "telPro":null
        }
      },
      {
        "idEquipe":1607307,
        "numero":1,
        "club":{
          "nom":"???",
          "code":null,
          "courriel":null,
          "lat":0.0,
          "lng":0.0,
          "correspondantClub":{
            "nomCorresp":"",
            "adresse1Corresp":null,
            "adresse2Corresp":null,
            "codePostalCorresp":null,
            "villeCorresp":null,
            "telBureauCorresp":null,
            "telDomicileCorresp":null,
            "telPortableCorresp":null,
            "courrielCorresp":null
          },
          "site":{
            "adresse1":null,
            "adresse2":null,
            "codePostal":null,
            "ville":null,
            "telephone":null,
            "nbCourtInt":null,
            "nbCourtExt":null,
            "lng":null,
            "lat":null
          }
        },
        "joueurs":[

        ],
        "correspondant":null
      }
    ],
    "classements":[
      {
        "nom":"GASTES TC 2",
        "place":1,
        "points":11,
        "nbRencontres":4,
        "matchesAverage":10,
        "setsAverage":19,
        "jeuxAverage":96,
        "pointsDePenalites":0
      },
      {
        "nom":"SARBAZAN ASL 1",
        "place":2,
        "points":11,
        "nbRencontres":4,
        "matchesAverage":8,
        "setsAverage":16,
        "jeuxAverage":76,
        "pointsDePenalites":0
      },
      {
        "nom":"LABOUHEYRE JEUNESSE SPORTIVE 3",
        "place":3,
        "points":8,
        "nbRencontres":4,
        "matchesAverage":0,
        "setsAverage":-1,
        "jeuxAverage":-4,
        "pointsDePenalites":0
      },
      {
        "nom":"PARENTIS EN BORN TC 2",
        "place":4,
        "points":6,
        "nbRencontres":4,
        "matchesAverage":-8,
        "setsAverage":-15,
        "jeuxAverage":-79,
        "pointsDePenalites":0
      },
      {
        "nom":"YCHOUX TC 2",
        "place":5,
        "points":4,
        "nbRencontres":4,
        "matchesAverage":-10,
        "setsAverage":-19,
        "jeuxAverage":-89,
        "pointsDePenalites":0
      },
      {
        "nom":"??? 1",
        "place":6,
        "points":0,
        "nbRencontres":0,
        "matchesAverage":0,
        "setsAverage":0,
        "jeuxAverage":0,
        "pointsDePenalites":0
      }
    ]
  },
  {
    "phase":{
      "phase":{
        "id":147637,
        "nom":"PHASE FINALE",
        "preliminaire":false,
        "tableau":true,
        "tailleDuTableau":2,
        "nombreDeTours":1,
        "allerRetour":false
      },
      "poule":null
    },
    "rencontres":[
      {
        "id":6562870,
        "codeClubAccueil":"59400240",
        "idPhase":147637,
        "position":1,
        "place":1,
        "equipe1":{
          "id":1597324,
          "codeClub":"59400201",
          "numero":2,
          "classement":0
        },
        "score1":3,
        "disqualification1":false,
        "equipe2":{
          "id":1598811,
          "codeClub":"59400240",
          "numero":2,
          "classement":0
        },
        "score2":0,
        "disqualification2":false,
        "equipeCenseeRecevoir":2,
        "inversee":false,
        "dateTheorique":"2018-11-18T00:00:00",
        "dateReelle":"2018-11-18T00:00:00",
        "resultat":"V",
        "equipeForfait":null
      }
    ],
    "detailsEquipes":[
      {
        "idEquipe":1597324,
        "numero":2,
        "club":{
          "nom":"BENESSE MAREMNE TC",
          "code":"59400201",
          "courriel":"09400201@fft.fr",
          "lat":43.63521,
          "lng":-1.36482,
          "correspondantClub":{
            "nomCorresp":"Monsieur PATRICK MONDENX",
            "adresse1Corresp":null,
            "adresse2Corresp":"689 ALLEE D'AOUCE",
            "codePostalCorresp":"40230",
            "villeCorresp":"BENESSE MAREMNE",
            "telBureauCorresp":null,
            "telDomicileCorresp":null,
            "telPortableCorresp":"0689783541",
            "courrielCorresp":"sarlttb@orange.fr"
          },
          "site":{
            "adresse1":null,
            "adresse2":"Allée des Corts",
            "codePostal":"40230",
            "ville":"BENESSE-MAREMNE",
            "telephone":"0558725188",
            "nbCourtInt":1,
            "nbCourtExt":3,
            "lng":-1.36482,
            "lat":43.63521
          }
        },
        "joueurs":[
          {
            "id":3749253,
            "classementSimpleLibelle":"30",
            "classementDoubleLibelle":"12",
            "niveauLibelle":null,
            "brule":false,
            "qualifieProvisoire":false,
            "assimileUe":false,
            "ordre":0,
            "nom":"BUTHAUD",
            "prenom":"EDOUARD",
            "licence":1145325,
            "ageReel":44
          },
          {
            "id":3727745,
            "classementSimpleLibelle":"30/2",
            "classementDoubleLibelle":"14",
            "niveauLibelle":null,
            "brule":false,
            "qualifieProvisoire":false,
            "assimileUe":false,
            "ordre":0,
            "nom":"LAHBIB",
            "prenom":"Eric",
            "licence":9077277,
            "ageReel":50
          },
          {
            "id":3727746,
            "classementSimpleLibelle":"30/2",
            "classementDoubleLibelle":"14",
            "niveauLibelle":null,
            "brule":false,
            "qualifieProvisoire":false,
            "assimileUe":false,
            "ordre":0,
            "nom":"MONDENX",
            "prenom":"Patrick",
            "licence":3953209,
            "ageReel":46
          },
          {
            "id":3727749,
            "classementSimpleLibelle":"30/3",
            "classementDoubleLibelle":"15",
            "niveauLibelle":null,
            "brule":false,
            "qualifieProvisoire":false,
            "assimileUe":false,
            "ordre":0,
            "nom":"DA SILVA",
            "prenom":"Serge",
            "licence":2590523,
            "ageReel":53
          },
          {
            "id":3727748,
            "classementSimpleLibelle":"30/3",
            "classementDoubleLibelle":"15",
            "niveauLibelle":null,
            "brule":false,
            "qualifieProvisoire":false,
            "assimileUe":false,
            "ordre":0,
            "nom":"REAU",
            "prenom":"Ludovic",
            "licence":826193,
            "ageReel":43
          },
          {
            "id":3727747,
            "classementSimpleLibelle":"30/3",
            "classementDoubleLibelle":"15",
            "niveauLibelle":null,
            "brule":false,
            "qualifieProvisoire":false,
            "assimileUe":false,
            "ordre":0,
            "nom":"GUILLY",
            "prenom":"Cedric",
            "licence":2515725,
            "ageReel":47
          },
          {
            "id":3727750,
            "classementSimpleLibelle":"30/4",
            "classementDoubleLibelle":"16",
            "niveauLibelle":null,
            "brule":false,
            "qualifieProvisoire":false,
            "assimileUe":false,
            "ordre":0,
            "nom":"DUMOLIÉ",
            "prenom":"Marc",
            "licence":9476612,
            "ageReel":51
          },
          {
            "id":3727752,
            "classementSimpleLibelle":"30/5",
            "classementDoubleLibelle":"17",
            "niveauLibelle":null,
            "brule":false,
            "qualifieProvisoire":false,
            "assimileUe":false,
            "ordre":0,
            "nom":"GAUD",
            "prenom":"GABRIEL",
            "licence":549554,
            "ageReel":45
          },
          {
            "id":3727751,
            "classementSimpleLibelle":"30/5",
            "classementDoubleLibelle":"17",
            "niveauLibelle":null,
            "brule":false,
            "qualifieProvisoire":false,
            "assimileUe":false,
            "ordre":0,
            "nom":"DO NASCIMENTO",
            "prenom":"Virgile",
            "licence":5943167,
            "ageReel":54
          },
          {
            "id":3727753,
            "classementSimpleLibelle":"40",
            "classementDoubleLibelle":"18",
            "niveauLibelle":null,
            "brule":false,
            "qualifieProvisoire":false,
            "assimileUe":false,
            "ordre":0,
            "nom":"SENAT",
            "prenom":"nicolas",
            "licence":3300239,
            "ageReel":36
          }
        ],
        "correspondant":{
          "nom":"M    EDOUARD BUTHAUD",
          "adresse1":"298 RUE DU BEAU SOLEIL",
          "adresse2":null,
          "codePostal":"40230",
          "ville":"BENESSE MAREMNE",
          "email":"edouard.buthaud@yahoo.com",
          "telPerso":null,
          "telPortable":"0686951470",
          "telPro":null
        }
      },
      {
        "idEquipe":1598811,
        "numero":2,
        "club":{
          "nom":"GASTES TC",
          "code":"59400240",
          "courriel":"09400240@fft.fr",
          "lat":44.32801,
          "lng":-1.1438,
          "correspondantClub":{
            "nomCorresp":"Monsieur cedric gauthier",
            "adresse1Corresp":null,
            "adresse2Corresp":"94 rue des galips",
            "codePostalCorresp":"40160",
            "villeCorresp":"parentis en born",
            "telBureauCorresp":null,
            "telDomicileCorresp":null,
            "telPortableCorresp":"0622092426",
            "courrielCorresp":"gauthiercedric9991@neuf.fr"
          },
          "site":{
            "adresse1":null,
            "adresse2":"rue Darmuzey",
            "codePostal":"40160",
            "ville":"GASTES",
            "telephone":"0622092426",
            "nbCourtInt":1,
            "nbCourtExt":4,
            "lng":-1.1438,
            "lat":44.32801
          }
        },
        "joueurs":[
          {
            "id":3731387,
            "classementSimpleLibelle":"30/1",
            "classementDoubleLibelle":"13",
            "niveauLibelle":null,
            "brule":false,
            "qualifieProvisoire":false,
            "assimileUe":false,
            "ordre":0,
            "nom":"SCHWINDOWSKY",
            "prenom":"Laurent",
            "licence":6176504,
            "ageReel":49
          },
          {
            "id":3731386,
            "classementSimpleLibelle":"30/1",
            "classementDoubleLibelle":"13",
            "niveauLibelle":null,
            "brule":false,
            "qualifieProvisoire":false,
            "assimileUe":false,
            "ordre":0,
            "nom":"LOPEZ PALACIOS",
            "prenom":"STEPHANE",
            "licence":6242702,
            "ageReel":41
          },
          {
            "id":3731384,
            "classementSimpleLibelle":"30/2",
            "classementDoubleLibelle":"14",
            "niveauLibelle":null,
            "brule":false,
            "qualifieProvisoire":false,
            "assimileUe":false,
            "ordre":0,
            "nom":"CARIOU",
            "prenom":"Frederic",
            "licence":2099198,
            "ageReel":46
          },
          {
            "id":3731385,
            "classementSimpleLibelle":"30/2",
            "classementDoubleLibelle":"14",
            "niveauLibelle":null,
            "brule":false,
            "qualifieProvisoire":false,
            "assimileUe":false,
            "ordre":0,
            "nom":"DEROOST",
            "prenom":"MICHEL",
            "licence":2920841,
            "ageReel":49
          },
          {
            "id":3731389,
            "classementSimpleLibelle":"30/3",
            "classementDoubleLibelle":"15",
            "niveauLibelle":null,
            "brule":false,
            "qualifieProvisoire":false,
            "assimileUe":false,
            "ordre":0,
            "nom":"LASSERRE",
            "prenom":"Bruno",
            "licence":5120001,
            "ageReel":48
          },
          {
            "id":3731388,
            "classementSimpleLibelle":"30/3",
            "classementDoubleLibelle":"15",
            "niveauLibelle":null,
            "brule":false,
            "qualifieProvisoire":false,
            "assimileUe":false,
            "ordre":0,
            "nom":"CHAPOUL",
            "prenom":"Franck",
            "licence":5715232,
            "ageReel":45
          },
          {
            "id":3731390,
            "classementSimpleLibelle":"30/4",
            "classementDoubleLibelle":"16",
            "niveauLibelle":null,
            "brule":false,
            "qualifieProvisoire":false,
            "assimileUe":false,
            "ordre":0,
            "nom":"LAMARQUE",
            "prenom":"David",
            "licence":2972330,
            "ageReel":39
          }
        ],
        "correspondant":{
          "nom":"M    Frederic CARIOU",
          "adresse1":"270 avenue Georges clémenceau",
          "adresse2":"16 avenue georges clémenceau",
          "codePostal":"40160",
          "ville":"PARENTIS EN BORN",
          "email":"cariou.frederic@neuf.fr",
          "telPerso":"0558785507",
          "telPortable":"0650469229",
          "telPro":null
        }
      }
    ],
    "classements":null
  }
],
  "hLib":"CD 40 - INTERCLUBS 35+ MESSIEURS 2019",
  "division":"DIVISION 7"
}
